name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    env:
      VITE_LAST_FM_KEY: ${{ secrets.VITE_LAST_FM_KEY }}
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version:  18.x
          
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Build
        run: |
          npm install
          npm run build
  
      - name: Deploy to GitHub Pages
        run: |
          # Assuming your build output is in the 'dist' directory
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout gh-pages
          rm -rf ./*
          mv ./dist/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
