name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    env:
      VITE_LAST_FM_KEY: ${{ secrets.VITE_LAST_FM_KEY }}
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version:  18.x
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build
          # Create an artifact from the build output directory (adjust the path as needed)
          # Upload the artifact to be used in the deploy step
          # You can adjust the name of the artifact as needed
          # The path should match the one used above (dist in this case)
          # You can upload multiple artifacts if needed, just add more "with" sections.
          # For example, for multiple artifacts:
          # uses: actions/upload-artifact@v2
          # with:
          #   name: my-artifact1
          #   path: dist
          uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: dist

  deploy:  
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Adjust the input for your specific use case
          branch: gh-pages
          folder: dist
          # Add any other options or environment variables required by the deploy action
          # For example, if you need to set up a custom domain:
          # cname: my-custom-domain.com
          # Or if you need to deploy to a subdirectory:
          # subdirectory: my-subdirectory
